repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-merge-conflict
#    - id: check-symlinks
    - id: detect-private-key
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-json
      types: [text]
      files: \.(json|tpl)$
    - id: pretty-format-json
      args: [--autofix]
      types: [text]
      files: \.(json|tpl)$
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3
      exclude: ^site-packages/*
